In [2]:
import numpy as np

arr = np.array(
    [[6, -8, 73, -110],  [np.nan, -8, 0, 94]]
    )

print("Display Original Array:")
print(arr)

# Replace NaN with 0
arr = np.nan_to_num(arr,nan=0)

print("\nAfter Replacing nan with 0:")
print(arr)

# Interchange rows and columns..............
a= arr.T

print("\nAfter Interchanging Rows and Columns:")
print(a)

Display Original Array:
[[   6.   -8.   73. -110.]
 [  nan   -8.    0.   94.]]

After Replacing nan with 0:
[[   6.   -8.   73. -110.]
 [   0.   -8.    0.   94.]]

After Interchanging Rows and Columns:
[[   6.    0.]
 [  -8.   -8.]
 [  73.    0.]
 [-110.   94.]]


In [3]:
import numpy as np

arr = np.arange(24).reshape(2, 3, 4)

print("Original Shape:", arr.shape)

# Move axis 0 to position 2
new_arr = np.moveaxis(arr, 0, 2)

print("New Shape:", new_arr.shape)
print(new_arr)

Original Shape: (2, 3, 4)
New Shape: (3, 4, 2)
[[[ 0 12]
  [ 1 13]
  [ 2 14]
  [ 3 15]]

 [[ 4 16]
  [ 5 17]
  [ 6 18]
  [ 7 19]]

 [[ 8 20]
  [ 9 21]
  [10 22]
  [11 23]]]


In [4]:
import numpy as np

a = np.array(
    [[10, np.nan, 30],
                [40, 50, np.nan],
                [70, 80, 90]]
)

print("Display original Array:")
print(a)

col_mean = np.nanmean(arr, axis=0)

# Find NaN positions
inds = np.where(np.isnan(arr))

# Replace NaN with column mean
arr[inds] = np.take(col_mean, inds[1])

print("\nArray After Replacing NaN with Column Mean:")
print(arr)

Display original Array:
[[10. nan 30.]
 [40. 50. nan]
 [70. 80. 90.]]

Array After Replacing NaN with Column Mean:
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [5]:
import numpy as np

arr = np.array([6, -8, 73, -110, 25, -5])

print("Original Array:")
print(arr)

arr[arr < 0] = 0

print("\nAfter Replacing Negative Values:")
print(arr)

Original Array:
[   6   -8   73 -110   25   -5]

After Replacing Negative Values:
[ 6  0 73  0 25  0]
