In [5]:
import numpy as np

arr = np.array([3,5,7,9,20,10])
arr2d = arr.reshape(2,3)

print(f"1D array : \n{arr}")
print(f"\nAfter conversion in 2-D : \n{arr2d}")

print("\n\nArray Attributes:")
print("Shape:", arr2d.shape)
print("Dimension:", arr2d.ndim)
print("Data Type:", arr2d.dtype)
print("Item Size:", arr2d.itemsize)

1D array : 
[ 3  5  7  9 20 10]

After conversion in 2-D : 
[[ 3  5  7]
 [ 9 20 10]]


Array Attributes:
Shape: (2, 3)
Dimension: 2
Data Type: int64
Item Size: 8


In [6]:
import numpy as np

a = np.full((3,3),9)

print(f"3 x 3 Array of 9's :\n{a}")

3 x 3 Array of 9's :
[[9 9 9]
 [9 9 9]
 [9 9 9]]


In [ ]:
# Create a 1D array of 10 evenly spaced values between 25 and 125
arr = np.linspace(25,125,10)
print(arr)

[ 25.          36.11111111  47.22222222  58.33333333  69.44444444
  80.55555556  91.66666667 102.77777778 113.88888889 125.        ]


In [ ]:
# Convert a Python list into a NumPy array

l = [10,20,70,80,90]

arr = np.array(l)
print(f"List to numpy Array :\n{arr}\nType : {type(arr)}")


List to numpy Array :
[10 20 70 80 90]
Type : <class 'numpy.ndarray'>


In [11]:
# Reverse a 1D NumPy array

arr = np.array(
    [2,4,6,9,0,10,7]
)

rev_arr = arr[::-1]
print("Original array :")
print(arr)
print("\nReverse array :")
print(rev_arr)

Original array :
[ 2  4  6  9  0 10  7]

Reverse array :
[ 7 10  0  9  6  4  2]


In [18]:
# Create a 4×4×3 array and extract value at its second set, first row and last column
arr = np.arange(48).reshape(4, 4, 3)
print("\n4x4x3 Array:")
print(arr)


print("\nSecond Set, First Row, Last Column:")
print(arr[1,0,2])


#  Slice first two rows and first two columns of second set from 4×4×3 array
print("\nFirst Two Rows and First Two Columns of Second Set:")
print(arr[1, :2, :2])





4x4x3 Array:
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]

 [[36 37 38]
  [39 40 41]
  [42 43 44]
  [45 46 47]]]

Second Set, First Row, Last Column:
14

First Two Rows and First Two Columns of Second Set:
[[12 13]
 [15 16]]


In [15]:
# 8. Create a 4×4 and Extract Odd Rows and Even Columns
arr = np.arange(1, 17).reshape(4, 4)

print("\n4x4 Array:")
print(arr)
print("\nOdd Rows and Even Columns:")
print(arr[0::2, 1::2])



4x4 Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Odd Rows and Even Columns:
[[ 2  4]
 [10 12]]


In [19]:
# 10. Replace all odd numbers with -1 using for loop
arr = np.array([[23, 56, 78, 93],
                [71, 82, 13, 24]])

for i in range(arr.shape[0]):
    for j in range(arr.shape[1]):
        if arr[i][j] % 2 != 0:
            arr[i][j] = -1

print("\nReplace Odd Numbers with -1:")
print(arr)




Replace Odd Numbers with -1:
[[-1 56 78 -1]
 [-1 82 -1 24]]


In [20]:
# 11. Get indices of non-zero elements
arr = np.array([1, 0, 2, 0, 3, 0, 4])

print("\nIndices of Non-Zero Elements:")
print(np.nonzero(arr))



Indices of Non-Zero Elements:
(array([0, 2, 4, 6]),)


In [21]:
# 12. Arithmetic Operations
arr1 = np.array([10, 20, 30])
arr2 = np.array([1, 2, 3])

print("\nAddition:")
print(arr1 + arr2)

print("\nMultiplication:")
print(arr1 * arr2)




Addition:
[11 22 33]

Multiplication:
[10 40 90]


In [22]:
# 13. Dot Product
arr1 = np.array([15, 20, 25])
arr2 = np.array([10, 40, 37])

dot_product = np.dot(arr1, arr2)

print("\nDot Product:")
print(dot_product)


Dot Product:
1875
