In [1]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([
    [4, 5, 6],
    [7, 8, 9]
])

combined = np.vstack((arr1, arr2))

print("Combined Array:")
print(combined)

Combined Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
import numpy as np

arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

# flat = arr.flatten()
newarr = arr.reshape(-1)

print("converted 1D Array:")
print(newarr)

converted 1D Array:
[1 2 3 4 5 6]


In [7]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

res = arr[::-1]

print("Reversed Array:")
print(res)

Reversed Array:
[50 40 30 20 10]


In [8]:
import numpy as np

arr = np.array([10, 20, 50, 30, 15])

print("Maximum Value:", np.max(arr))
print("Minimum value :",np.min(arr))

Maximum Value: 50
Minimum value : 10


In [9]:
import numpy as np

arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

rows, cols = arr.shape

print("Rows =", rows)
print("Columns =", cols)

Rows = 2
Columns = 3


In [11]:
import numpy as np

a = np.array([
    [23,4,5,78],
    [45,7,79,4]
])

print("array element :")
for i in a:
    for j in i:
        print(j)


print("3rd element of 2nd Row :")
print(a[1,1])

array element :
23
4
5
78
45
7
79
4
3rd element of 2nd Row :
7


In [12]:
import numpy as np

a = np.array([
    [23,4,5,78],
    [45,7,79,4]
])


print("sum of the array is :")

total =0
for row in a:
    for j in row :
        total+=j

print(total)

sum of the array is :
245


In [19]:
import numpy as np
 
a1 = np.array([100,45,20])
a2 =np.array([15,10,25])

print(f"Addition of 2 array : {a1+a2}")
print(f"suntraction of 2 array : {a1-a2}")
print(f"Multiplication of 2 array : {a1*a2}")
print(f"Division of 2 array : {a1/a2}")


Addition of 2 array : [115  55  45]
suntraction of 2 array : [85 35 -5]
Multiplication of 2 array : [1500  450  500]
Division of 2 array : [6.66666667 4.5        0.8       ]


In [23]:
import numpy as np

arr = np.array([
    [[2,4],[5,7]],
    [[3,7],[4,9]]
]
)
print(arr)

print(f"\n each element :")
for i in arr:
    for j in i:
        for k in j:
            print(k)

[[[2 4]
  [5 7]]

 [[3 7]
  [4 9]]]

 each element :
2
4
5
7
3
7
4
9


In [ ]:
import numpy as np

arr = np.array([
    [[2,4],[5,7]],
    [[3,7],[4,9]]
]
)

print("each element using nditer func:")
for x in np.nditer(arr):
    print(x)

2
4
5
7
3
7
4
9


In [25]:
import numpy as np

arr1 = np.array([
    [10, 20],
    [30, 40]
])

arr2 = np.array([
    [50, 60],
    [70, 80]
])

avg = (arr1 + arr2) / 2

print("Average Array:")
print(avg)

com_arr = np.concatenate((arr1.flatten(), arr2.flatten()))

mean = np.mean(com_arr)
median = np.median(com_arr)

values, counts = np.unique(com_arr, return_counts=True)
mode = values[np.argmax(counts)]

print("\nMean =", mean)
print("Median =", median)
print("Mode =", mode)

Average Array:
[[30. 40.]
 [50. 60.]]

Mean = 45.0
Median = 45.0
Mode = 10
